"""empty message

Revision ID: 9cddafef9f41
Revises: b1da6ff4a8af
Create Date: 2026-06-06 22:05:58.465485

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '9cddafef9f41'
down_revision: Union[str, Sequence[str], None] = 'b1da6ff4a8af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
