"""empty message

Revision ID: b176c1ec7f7b
Revises: 2cb5f1dde2eb
Create Date: 2026-05-04 19:33:02.154456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b176c1ec7f7b'
down_revision: Union[str, Sequence[str], None] = '2cb5f1dde2eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('defense_slot',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('time_start', sa.DateTime(), nullable=False),
    sa.Column('time_end', sa.DateTime(), nullable=False),
    sa.Column('max_expert', sa.Integer(), nullable=False),
    sa.Column('max_customers', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curator',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('defense_room',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('curator_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['curator_id'], ['curator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expert_registration',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('expert_id', sa.UUID(), nullable=False),
    sa.Column('defense_slot_id', sa.UUID(), nullable=False),
    sa.Column('defense_room_id', sa.UUID(), nullable=False),
    sa.Column('role_at_registration', sa.String(length=100), nullable=True),
    sa.Column('registered_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['defense_room_id'], ['defense_room.id'], ),
    sa.ForeignKeyConstraint(['defense_slot_id'], ['defense_slot.id'], ),
    sa.ForeignKeyConstraint(['expert_id'], ['expert.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_link',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('GITHUB', 'GITLAB', 'OTHER_REPO', 'WEB', 'MOBILE_APP', 'ADMIN_PANEL', 'API_DOCS', 'DESIGN', 'DOCUMENTATION', 'PRESENTATION', 'DATABASE_SCHEMA', 'ANALYTICS', 'VIDEO_DEMO', 'OTHER', name='projectlinktype'), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_member',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('role_in_team', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('protocol',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('defense_slot_id', sa.UUID(), nullable=False),
    sa.Column('defense_room_id', sa.UUID(), nullable=False),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], ),
    sa.ForeignKeyConstraint(['defense_room_id'], ['defense_room.id'], ),
    sa.ForeignKeyConstraint(['defense_slot_id'], ['defense_slot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slot_to_room',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('defense_slot_id', sa.UUID(), nullable=False),
    sa.Column('defense_room_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['defense_room_id'], ['defense_room.id'], ),
    sa.ForeignKeyConstraint(['defense_slot_id'], ['defense_slot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_registration',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_member_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('defense_slot_id', sa.UUID(), nullable=False),
    sa.Column('defense_room_id', sa.UUID(), nullable=False),
    sa.Column('registered_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['defense_room_id'], ['defense_room.id'], ),
    sa.ForeignKeyConstraint(['defense_slot_id'], ['defense_slot.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['project_member_id'], ['project_member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('final_score',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_registration_id', sa.UUID(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_registration_id'], ['student_registration.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_registration_id')
    )
    op.create_table('grade',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('expert_id', sa.UUID(), nullable=False),
    sa.Column('student_registration_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('text_questions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['expert_id'], ['expert.id'], ),
    sa.ForeignKeyConstraint(['student_registration_id'], ['student_registration.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grade')
    op.drop_table('final_score')
    op.drop_table('student_registration')
    op.drop_table('slot_to_room')
    op.drop_table('protocol')
    op.drop_table('project_member')
    op.drop_table('project_link')
    op.drop_table('expert_registration')
    op.drop_table('project')
    op.drop_table('defense_room')
    op.drop_table('curator')
    op.drop_table('defense_slot')
    # ### end Alembic commands ###
