"""empty message

Revision ID: f80c349654de
Revises: 9a5845e47362
Create Date: 2026-06-06 13:36:16.930829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f80c349654de'
down_revision: Union[str, Sequence[str], None] = '9a5845e47362'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'curator_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'curator_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
