from uuid import UUID
from typing import Protocol

from typing import Optional, List

from pydantic import BaseModel

from src.repositories import BaseRepositoryPort
from src.users.schemas import (
    UserAuthenticationResponse,
    UserAuthenticationRequest,
)
from src.users.models import User
from sqlalchemy.ext.asyncio import AsyncSession


class UserRepositoryPort(BaseRepositoryPort):
    def __init__(self, model: type[User], session: AsyncSession) -> None: ...
    async def get_by_id(self, id: UUID) -> Optional[User]: ...
    async def get_all(self, skip: int = 0, limit: int = 100) -> List[User]: ...
    async def create(self, obj: User) -> User: ...
    async def update(self, obj: User) -> User: ...
    async def delete(self, obj: User) -> None: ...
    
    async def get_by_email(self, user_email: str) -> Optional[User]: ...
    async def email_exists(self, user_email: str) -> bool: ...
    
    async def get_user_with_profiles(self, user_id: UUID) -> User | None: ...


class UserServicePort(Protocol):
    async def register(self, user: UserAuthenticationRequest) -> UserAuthenticationResponse: ...
    async def login(self, user: UserAuthenticationRequest) -> UserAuthenticationResponse: ...
    async def get_user_by_email(self, email: str) -> str | None: ...
    async def send_email_code(self, email: str) -> None: ...
    async def verify_email_code(self, email: str, code: str) -> None: ...

    async def get_full_profile(self, user_id: UUID) -> BaseModel: ...


class RoleSerializerPort(Protocol):
    """Контракт для сериализации профиля конкретной роли."""
    def is_applicable(self, user: "User") -> bool: ...
    def serialize(self, user: "User") -> BaseModel: ...
