class AuthError(Exception): ...


class UserAlreadyExistsError(Exception): ...
class IncorrectPassword(Exception): ...


class UserNotFoundError(Exception): ...

class TooManyVerificationAttemptsError(Exception): ...

class InvalidVerificationCodeError(Exception): ...
class VerificationCodeExpiredError(Exception): ...
class VerificationCodeNotFoundError(Exception): ...