from typing import Optional, List, Any, Protocol

from src.repositories import BaseRepositoryPort

from uuid import UUID

from src.projects.models import Project, ProjectLink, ProjectMember
from src.projects.schemas import (
    ProjectCreateRequest, ProjectFullSchemaResponse, ProjectCalendarItemResponse, 
    ProjectLink as ProjectLinkSchema, ProjectMemberSchema, CuratorSchema
)


class ProjectRepositoryPort(BaseRepositoryPort):
    async def get_projects_calendar(self) -> List[Project]: ...
    
    async def get_project_with_details(self, project_id: UUID) -> Optional[Project]: ...

    async def get_project_links(self, project_id: UUID) -> List[ProjectLink]: ...

    async def get_project_team(self, project_id: UUID) -> List[ProjectMember]: ...
    
    async def get_student_id_by_user_id(self, user_id: UUID) -> Optional[UUID]: ...

    async def create_project_with_creator(self, project: Project, creator_student_id: UUID, creator_role: str) -> Project: ...

    async def update_project(self, project: Project) -> Project: ...
    
    async def delete_project(self, project_id: UUID) -> None: ...
    
    # Links
    async def get_link_by_id(self, project_id: UUID, link_id: UUID) -> Optional[ProjectLink]: ...

    async def add_project_link(self, link: ProjectLink) -> ProjectLink: ...
    
    async def update_project_link(self, link: ProjectLink) -> ProjectLink: ...

    async def delete_project_link(self, project_id: UUID, link_id: UUID) -> None: ...
    
    async def delete_all_project_links(self, project_id: UUID) -> None: ...
    
    # Team
    async def get_member_by_id(self, project_id: UUID, member_id: UUID) -> Optional[ProjectMember]: ...

    async def add_project_member(self, member: ProjectMember) -> ProjectMember: ...
    
    async def update_project_member(self, member: ProjectMember) -> ProjectMember: ...

    async def delete_project_member(self, project_id: UUID, member_id: UUID) -> None: ...

    async def delete_all_project_members(self, project_id: UUID) -> None: ...

    # Curator
    async def update_project_curator(self, project_id: UUID, curator_id: UUID) -> Optional[Project]: ...
    
    async def remove_project_curator(self, project_id: UUID) -> Optional[Project]: ...


class ProjectServicePort(Protocol):
    async def get_projects_calendar(self) -> List[ProjectCalendarItemResponse]: ...
        
    async def get_project_info(self, project_id: UUID) -> Any: ...

    async def get_project_links(self, project_id: UUID) -> List[ProjectLinkSchema]: ...

    async def get_project_team(self, project_id: UUID) -> List[ProjectMemberSchema]: ...

    async def create_project(self, project_data: ProjectCreateRequest) -> Any: ...

    async def update_project(self, project_id: UUID, project_data: ProjectFullSchemaResponse) -> Any: ...

    async def delete_project(self, project_id: UUID) -> None: ...

    async def add_project_link(self, project_id: UUID, link_data: ProjectLinkSchema) -> ProjectLinkSchema: ...

    async def update_project_link(self, project_id: UUID, link_id: UUID, link_data: ProjectLinkSchema) -> ProjectLinkSchema: ...

    async def delete_project_link(self, project_id: UUID, link_id: UUID) -> None: ...

    async def delete_all_project_links(self, project_id: UUID) -> None: ...

    async def add_project_member(self, project_id: UUID, member_data: ProjectMemberSchema) -> ProjectMemberSchema: ...

    async def update_project_member(self, project_id: UUID, member_id: UUID, member_data: ProjectMemberSchema) -> ProjectMemberSchema: ...

    async def delete_project_member(self, project_id: UUID, member_id: UUID) -> None: ...

    async def add_project_curator(self, project_id: UUID, curator_data: CuratorSchema) -> CuratorSchema: ...

    async def update_project_curator(self, project_id: UUID, curator_data: CuratorSchema) -> CuratorSchema: ...

    async def remove_project_curator(self, project_id: UUID) -> None: ...
